version: "3"

services:
    django:
        build: .
        command: gunicorn personal_expenses.wsgi:application --bind 0.0.0.0:8000
        container_name: "djangosystem"        
        expose:
            - 8000
        env_file: 
            - ".env"
        network_mode: host
        
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - django
        network_mode: host
        environment: 
            - VIRTUAL_HOST=personal-expenses.migueldnt.dev
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=personal-expenses.migueldnt.dev
            - LETSENCRYPT_EMAIL=miguel.danto@gmail.com
               
        

