version: "3"

services:
    django:
        build: .
        command: gunicorn personal_expenses.wsgi:application --bind 0.0.0.0:8000
        container_name: "djangosystem"        
        expose:
            - 8000
        env_file: 
            - ".env"
        
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:80
        depends_on:
            - django
               
        

